spring.application.name=SmartRateLimiter
spring.datasource.username=SAM
spring.datasource.password=PASSWORD
spring.datasource.url=jdbc:postgresql://localhost:5332/smartratelimiter
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.ssl.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.security.user.name=Sammonnay
spring.security.user.password=password123
jwt.secret=a7f3k9p2m8q1n6r4t0w5y2x8z3b6c1d4e7f0g3h6i9j2k5l8m1n4o7p0q3r6s9t2
jwt.expiration=86400000
rate.limiter.algorithm=token_bucket
# rate.limiter.algorithm=fixed_window